### ISSUE TITLE
Versions went backwards: 0.91 from 3 years ago is higher than the current 0.14.1

### ISSUE THREAD

**Issue by yurivict** [PixarAnimationStudios/OpenTimelineIO#1208]
Update auto-discovering system finds the old version as new.

Could you please remove old higher tags?

**Comment by JeanChristopheMorinPerso** [comment]
@jminor @reinecke @meshula @ssteinbach This one is for you.

There seems to be a v0.91 tag, see https://github.com/PixarAnimationStudios/OpenTimelineIO/releases/tag/v0.91.

Diff between 0.10 and 0.9: https://github.com/PixarAnimationStudios/OpenTimelineIO/compare/v0.9...v0.10
Diff between 0.91 and 0.9: https://github.com/PixarAnimationStudios/OpenTimelineIO/compare/v0.9...v0.91

0.91 looks like a test or something? Because it';s not in PyPI and the last commit is the commit that bumped the version to 0.10.

**Comment by meshula** [comment]
yeah, I think that release was erroneously not 0.9.1. should probably delete the tag and re-tag

**Comment by jminor** [comment]
When I navigate to that commit, I see the message "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

https://github.com/PixarAnimationStudios/OpenTimelineIO/commit/8211ce2dca726a9560b0bd1b4c23f20e590a8922

Same here:
https://github.com/PixarAnimationStudios/OpenTimelineIO/tree/v0.91

I will see if I can simply delete the v0.91 tag.

---
Joshua Minor (he-him)
Pixar Studio Tools Story/Editorial/VR Previs Tech Lead
***@***.***

**Comment by jminor** [comment]
Deleted. @yurivict did that resolve the problem for you?

**Comment by yurivict** [comment]
Yes, thanks.
