### ISSUE TITLE
Upgrade otioview to PySide6

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#1215]
Currently otioview uses PySide2, which is quite old. In some newer versions of Python, or newer hardware (e.g. Mac M1) it is difficult to build or install PySide2. We should upgrade otioview to PySide6 (so named since it uses Qt 6).

At first glance, the API seems to have only minimal changes between PySide2 and PySide6, so maybe otioview could be made to work with both? If someone can do the port to PySide6, then we can judge if making it work on both is possible.

This might also be a good time to re-examine #616

**Comment by timlehr** [comment]
We had an internal OTIO presentation today and some of our departments expressed interest in using parts of otioview as a widget in our apps. Since we’re using PyQt (not PySide) we’d have to adapt the code a little, which is why making #616 a reality would be awesome. Since Qy.py doesn't support PySide6 yet, some work would need to be done on that end first though. I'd be happy to port the otioview code to Qt.py, but I don't think I can spare the time to make the shim work with PySide6 right now.
