### ISSUE TITLE
Attribute error on opentimelineview.Details widget: unicode object has no attribute 'indexOf'

### ISSUE THREAD

**Issue by bpeck** [PixarAnimationStudios/OpenTimelineIO#272]
Win10, Python 2.7.13
When clicking on timeline sections in otioview tool, the following exception is thrown every time a section is clicked:

> Traceback (most recent call last):
  File "Z:\dist\third_party\apps\python\2.7\lib\site-packages\opentimelineview\details_widget.py", line 110, in highlightBlock
    firstQuoteIndex = text.indexOf('"', index)

Replacing `indexOf` with `index` fixes the problem. I believe maybe this is a typo, since there are lots of use of QRegExp.indexIn elsewhere? But maybe it's a py2.7 issue, not sure.

**Comment by jminor** [comment]
There is some odd mixture of Qt4 and Qt5 in the code at the moment, which is likely the culprit here. Some code is expecting a QString vs Python string. Hopefully we will be able to land #160 soon to resolve these issues.

Can you check to see which version of Qt you are using? That could help ensure that my guess is correct.

**Comment by ssteinbach** [comment]
We've landed #160 - if you have a second, can you take another look and see if that got fixed for you?

**Comment by bpeck** [comment]
Hey sorry, I must have my notification settings set badly, just saw this now. Thanks for addressing!
