### ISSUE TITLE
Track ordering clarification

### ISSUE THREAD

**Issue by alatdneg** [PixarAnimationStudios/OpenTimelineIO#277]
Hi all, 
~~I'm seeing some confusing behaviour when ordering tracks, otioview.py seems to be reversing the audio tracks when using the AAF reader.~~

In fact it's all a bit confusing, when different apps expect different track orders, I'm not sure if anywhere in the otio spec it's made clear.

There are a bunch of ways, to do this but which one is otio and the various handlers expecting?
As read from otio
[ Va, Vb, Aa, Ab]

should it be..
Va
Vb
Aa
Ab

or

Vb
Va
Ab
Aa

etc. 
cheers!

**Comment by jminor** [comment]
We waffled on this early on, so I'm not surprised that the ordering isn't clearly documented. The confusion arises from the fact that video tracks, V1, V2, V3, etc. are typically ordered with V1 on the bottom, but audio tracks have A1 on the top - at least visually in the UIs we have been using for design reference.

In the unit tests you can see that tracks with a higher index obscure tracks with lower indexes when flattening. That means that `track[0]` is the bottom and `track[n-1]` is the top.

Looking at the diagrams here: https://github.com/PixarAnimationStudios/OpenTimelineIO/wiki/OTIO-Timeline-Structure we have them listed backwards. Oops.

Since we're still beta, we *could* change this. We will at least fix the documentation to match the implementation. Do you have a strong opinion about which way is the most intuitive or correct?

**Comment by alatdneg** [comment]
I'd go with the current set up it sort of makes sense that appending to the array with audio or video adds to the top / bottom of each respective media type.

But definitely make it very clear in the docs how this is expected to work, or people are going to get very confused.

So  my example would be ..

[Va,Vb,Aa,Vc,Ab] = 

Vc
Vb
Va
Aa
Ab

Appending [Vd,Ac] to the stack =

Vd
Vc
Vb
Va
Aa
Ab
Ac

**Comment by alatdneg** [comment]
In which case the AAF reader is probably reporting the audio tracks in the wrong order.
