### ISSUE TITLE
Should track_algo.track_with_expanded_transitions() return a Track instead of a list?

### ISSUE THREAD

**Issue by apetrynet** [PixarAnimationStudios/OpenTimelineIO#371]
Hi!
While working on #363 I discovered that `track_algo.track_with_expanded_transitions()` returns a new "track" based on an empty list. Should this be an actual schema.Track?  
```
def track_with_expanded_transitions(in_track):
    """Expands transitions such that neighboring clips are trimmed into
    regions of overlap.

    For example, if your track is:
        Clip1, T, Clip2

    will return:
        Clip1', Clip1_t, T, Clip2_t, Clip2'

    Where Clip1' is the part of Clip1 not in the transition, Clip1_t is the
    part inside the transition and so on.
    """

    #result_track = []
    result_track = schema.Track(kind=in_track.kind)
    ...
```
The reason I'm asking is that when trying to figure out if a Clip's parent is an audio track I don't get a valid result when calling item.parent(). This I believe is because it's not from a proper Track.

**Comment by apetrynet** [comment]
I got this working by changing another line in the same function replacing
`result_track.append(_expand_transition(thing, in_track))` with `result_track.extend(_expand_transition(thing, in_track))` 

Also had to do some tweaks to the indexing in test_track_algo.test_expand_surrounded_by_clips(self) to make all test pass.

Should I create a PR for this so you can check it out?

**Comment by ssteinbach** [comment]
Its a good question, and if we don't make it return a track we should at least explain why we aren't returning a track back.

In a track, transitions are next to items and "eat into" the items  they're next to.  Given a track like this:
`[A, B, t, C, D]`

Where `A`, `B`, `C`, and `D` are clips and `t` is a transition, `track_with_expanded_transitions()` will return a list like this:
`[A, B', (Bt, t, Ct), C', D]`

Where `B'` is everything in `B` outside the transition, `Bt` is the chunk of `B` that is inside the transition.

This doesn't really follow the behavior of a track because the `(Bt, t, Ct)` tuple plays at the same time, with whatever the transition is applied to it.  It also makes it easy to find the parts of the track that are 'inside' the transition.

I think we should probably rename this function so that it doesn't sound like it returns a track.  In your case, can you cache whether it was audio or video before you pass it in?  What are you doing with these objects?

**Comment by apetrynet** [comment]
Hi! 
Thanks you your insights. 
I'm working on support for audio clips in the RV adapter. In the adapter I want to use the `Clips.parent()` method to determine if it lives in an AudioTrack or not. 
The clips in the list returned from `track_with_expanded_transitions()` yield None when `parent()` is called.

> In your case, can you cache whether it was audio or video before you pass it in? What are you doing with these objects?

Yes, I most definitely can. I can't understand why I didn't think of that. (palm face)
Thanks again!

**Comment by apetrynet** [comment]
I'll close this for now.
