### ISSUE TITLE
AttributeError: TimeRange is Immutable.

### ISSUE THREAD

**Issue by alatdneg** [PixarAnimationStudios/OpenTimelineIO#408]
Why is it immutable ? It makes my code fail all over the place.

This seems like a perfectly reasonable operation.

```
head = from_frames(5, extract_range.start_time.rate)
extract_range.start_time -= head

```
It now has to be
`extract_range.start_time = extract_range.start_time - from_frames(5, extract_range.start_time.rate)
`
Which seems a bit odd.

**Comment by alatdneg** [comment]
I'd understand making the guts hidden, i.e. value and rate, shouldn't really access those directly, but you should be able to use overloaded operators.

**Comment by alatdneg** [comment]
Ah TimeRange is also immutable, argh. This really breaks a lot of code.

**Comment by alatdneg** [comment]
I have a lot of code that does things like
`time_range.start_time += from_frames(10, time_range.start_time.rate)`

With this new set up it becomes
`time_range = TimeRange(time_range.start_time +  from_frames(10, time_range.start_time.rate), time_range.duration)
`
Is there really no better solution, as this just seems messy.

**Comment by alatdneg** [comment]
Ah I see RationalTime still allows += as it just replaces the object, but TimeRange doesn't work as it has no exposed functions to modify it's duration/start_time maybe some helpers to do this ?

**Comment by jminor** [comment]
@alatdneg sorry for the disruption. We did this for a few reasons:
- To aid the C++ port, which will soon be layered under the python implementation.
- To avoid some insidious bugs that some people were encountering when they accidentally reused a TimeRange in multiple places and then modified them all when intending to modify just one.
- To set us up for future optimizations, specifically so that we will be able to cache the composition timing computations if needed. Doing so while allowing any TimeRange or RationalTime to be mutated would require callbacks all the way down at the field level of these which would be problematic.

I agree that constructing a new TimeRange just to change one thing feels awkward. Do you have any suggestions for helper functions that would make this cleaner? Perhaps `extended_by()` and `offset_by()` or maybe the union & intersection operators that @meshula suggested here https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/367#issuecomment-443476202

**Comment by alatdneg** [comment]
Yep fair enough, those helpers sound fine.  I guess union etc. might also work, but they might not be so clear.
