### ISSUE TITLE
RationalTime::is_valid method

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#573]
Small function to make sure that neither rate nor value are invalid.

**Comment by Shankusu993** [comment]
Hello Mr. @ssteinbach , I would like to fix this issue. To do so I would like to know are we looking to add a method to verify at any time that my object has valid rate and value or we want it to be initialized with valid parameters. I ask this because from my understanding of this #550  requires a similar validation of rate but only during initialization. So If you can let me know what exactly needs to be done , I would be more than happy to fix both the issues together.

**Comment by jminor** [comment]
There's already an `is_invalid_time()` method here: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/opentime/rationalTime.h#L25

It could be enhanced to check for NaN rate or value.

**Comment by Shankusu993** [comment]
I initially missed the `is_invalid_time()`  method.  Alright, So can I go ahead with doing the enhancements to check if they're NaN?

**Comment by hisergiorojas** [comment]
@ssteinbach I want to work on this issue.

**Comment by jminor** [comment]
Thanks @hisergiorojas - we got your signed CLA. If you want to work on this issue, feel free to submit a pull request for review.
