### ISSUE TITLE
CMX 3600 - Save record in/out

### ISSUE THREAD

**Issue by flavienliger** [PixarAnimationStudios/OpenTimelineIO#647]
Hi,
I'm using your great tool for convert EDL to CSV, merge EDL, ...

But I've tweaked the cmx_3600 adapter, because you don't save the record in and out into the clip.
Is It any reason for that ?

For be more specific I'm talking about this :
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/afc69b96c7908b29c2334994e6c4404073d95fc7/src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py#L144-L151

Thanks.

**Comment by jminor** [comment]
In OTIO, the record in/out for a clip is computed instead of stored. This means that you can modify a clip or track or whatever without fear that a stored record in/out of everything else becomes out of date. In other words, you can read an EDL, modify your timeline, and then write it out without having to manually recompute record times.

You can ask OTIO to compute the record range of a clip like this:
`record_range = clip.transformed_time_range(clip.trimmed_range(), timeline.tracks)`

or if you know the clip is not nested, then this simpler form works:
`record_range = clip.trimmed_range_in_parent()`

Then to get the record in/out as timecode, you can do this:
```record_rate = record_range.start_time.rate
record_in = opentime.to_timecode(record_range.start_time, record_rate)
record_out = opentime.to_timecode(record_range.end_time_exclusive(), record_rate)
```

You can see the EDL writer does this same thing here: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py#L949

**Comment by flavienliger** [comment]
Oh cool thank you ! 

I've tested many things but I didn't find the solution. And now I'm understanding why it works like that.
