### ISSUE TITLE
OtioView should indicate the presence of empty tracks

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#654]
While debugging #650, otioview has blank lines but they don't read.  Better to draw the track widet with `EMPTY TRACK` or something on it so that its clear that there are tracks there, they simply contain no data.

**Comment by KarthikRIyer** [comment]
@ssteinbach I'd like to give this a try.

I think showing an empty track should be good enough because it seems clear that an empty track is present even of we don't put anything there.

I think modifying this part by removing the check on `list(t)` should do the trick.

```python
        if isinstance(self.composition, otio.schema.Stack):
            video_tracks = [
                t for t in self.composition
                if t.kind == otio.schema.TrackKind.Video and list(t)
            ]
            audio_tracks = [
                t for t in self.composition
                if t.kind == otio.schema.TrackKind.Audio and list(t)
            ]
```

It gives me something like this (one empty video track and one empty audio track):

![image](https://user-images.githubusercontent.com/35020024/76892165-40dd5000-68b0-11ea-8667-cc355ec0841f.png)

**Comment by KarthikRIyer** [comment]
@ssteinbach does this seem right?

**Comment by KarthikRIyer** [comment]
Any thoughts on this?

**Comment by jminor** [comment]
It would be more clear with a label of some kind. Instead of "Empty Track" maybe we could add the names of the tracks on the left? That would also help people distinguish the audio and video tracks from each other.
