### ISSUE TITLE
Cannot deserialize Clip without media_reference

### ISSUE THREAD

**Issue by mikemahony** [PixarAnimationStudios/OpenTimelineIO#670]
We have a bunch of OTIO JSON files on disk that lack Clip `media_reference` keys.  Our users often need to manually edit/verify timelines and, since the keys weren’t necessary before the `0.12` release (note: we use `metadata` to retarget in a media linker), sparse JSON has helped significantly.

I see ([here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/61361db8878aaf2efc9bd0ffccf773831dff3a2a/src/opentimelineio/clip.cpp#L23)) that a new Clip will default `media_reference` to `MissingReference`.  It appears, however, that deserializing this sparse JSON fails when `Clip::read_from`'s `reader.find` throws a `KEY_NOT_FOUND` error.

Should Clip deserialization also default missing `media_reference`s to `MissingReference`?

**Comment by reinecke** [comment]
I'm pretty into the tolerant reader/robustness pattern as long as it doesn't create unexpected behavior.
I think adding a `MIssingReference` to a "naked" clip is unlikely to create confusion so I don't mind adding this behavior. I suppose we should consider it part of the specification in that case.

Does anyone have an argument against it?

**Comment by ssteinbach** [comment]
The only thing about that is it is inconsistent with the behavior of the rest of the API- when you instantiate an `otio.schema.Clip` you get a `MissingReference` automatically in the `media_reference` property.  I guess the question is about how permissive to make the parser.  We allow none for the ranges and have the default read, so unless there is a good reason to avoid this kind of a pattern.  It does make the files slightly more difficult to read, since you'll have a clip with no media reference.

**Comment by jminor** [comment]
When we write out OTIO files we include all the fields for two reasons:
- Clarity when learning what *can* be in an OTIO. Simplly looking at the file shows you all the available fields, rather than requiring reference to the docs or code.
- Protection against future changes to default values.

Reading a file with missing fields transformed into their default values can help in a practical sense, but it runs the risk of misunderstanding what the file intended. For example, code that treats a missing media_reference as None, versus as a MissingReference will behave differently, so you might have unintended consequences if the default changes sometime after your file is made.

**Comment by jminor** [comment]
In this particular case, we recommend using MissingReference instead of None, so that you can hold metadata on it, even though you don't know where the media is.

**Comment by mikemahony** [comment]
Thank you for discussing, everyone! I hope I'm not missing something obvious - apologies if I am...

How about this?
1. Continue to include all fields on OTIO json write.
2. On OTIO json read:
	A. Fields set to `null` are treated as `None`.
	A. Missing fields are added and set to their default value.

In this scenario the following would pass:
```
def test_ref_deserialized_default(self):
    decoded = otio.adapters.otio_json.read_from_string(
        '{'
        '  "OTIO_SCHEMA":"Clip.1",'
        '  "media_reference": {'
        '    "OTIO_SCHEMA": "MissingReference.1",'
        '    "metadata": {'
        '      "test": "ok"'
        '    }'
        '  }'
        '}'
    )
    self.assertIsOTIOEquivalentTo(
        decoded.media_reference,
        otio.schema.MissingReference(
            metadata={
                "test": "ok"
            }
        )
    )

    decoded = otio.adapters.otio_json.read_from_string(
        '{ "OTIO_SCHEMA":"Clip.1", "media_reference":null }'
    )
    self.assertEqual(
        decoded.media_reference,
        None
    )

    decoded = otio.adapters.otio_json.read_from_string(
        '{ "OTIO_SCHEMA":"Clip.1" }'
    )
    self.assertIsOTIOEquivalentTo(
        decoded.media_reference,
        otio.schema.MissingReference()
    )
```

This sample means what it says: "The media reference can point to nothing and, if it's missing altogether, it's missing."  Or, in other words, isn't excluding the field altogether in the source json the same as instantiating an `otio.schema.Clip` without a `media_reference` argument, implying that you get a `MissingReference` automatically in the `media_reference` property when parsed?

I'm in favor of this proposal because:
1. Users who have not pruned their json will be protected from changes to defaults.
2. Users who do manually manipulate their json have the option of being terse while maintaining control over their object values and benefiting from defaults.

Thanks again for talking this out with me!

**Comment by jminor** [comment]
It sounds like we still have reservations about allowing missing keys in the JSON. The current implementation throws an error when a Clip's media_reference is missing, which is causing some grief for folks who prune their JSON intentionally.

Here's a thought about how to accommodate this with clearly defined behavior: Maybe we could make media_reference optional for Clip.1, but required for Clip.2 and above. That would let us still read these existing files, and use the schema upgrade mechanism to apply the default value, and also ensure that there is no ambiguity moving forward.

**Comment by reinecke** [comment]
We've decided we'd like for OTIO files to be explicit about null media references.
