### ISSUE TITLE
add a clang format file

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#706]
A clang format file would be nice, perhaps we can use the one from OpenEXR as a starting point.

**Comment by meshula** [comment]
the whitespace between the function name and the parentheses is a historical peculiarity of codebases that conform to old Silicon Graphics standards. I believe everyone is in agreement that the rule should be modified for OTIO to NOT have that space.

**Comment by meshula** [comment]
aside from the idiosyncratic space, the file does look nice.

**Comment by ssteinbach** [comment]
I think this issue should include:

- [ ] the clang format file (as already discussed)
- [ ] a target in the `Makefile` that runs the clang format in such a way that it fails if changes are needed (similar to this and the way that the python linters are run): https://stackoverflow.com/questions/22866609/can-clang-format-tell-me-if-formatting-changes-are-necessary
- [ ] a target that runs clang-format for you on the c++ files in the repo
- [ ] integrate the ^ run with `make lint` target-- https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/e7a52a418695cb6c0407637917f23fd5b34fee60/Makefile#L100
- [ ] add them into the CI runs, next to the python linting: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/e7a52a418695cb6c0407637917f23fd5b34fee60/setup.cfg#L69
- [ ] make sure that the clang-format file goes into the right place so that IDEs like Xcode, VS, and CLion detect the file correctly
