### ISSUE TITLE
C++ API

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#71]
The Python API is fine for many studio use cases, but for embedding OTIO into a 3rd party application, a C API is preferred.

We should use a library like libgit2 as a model for how the C API should work (e.g. minimal dependencies, re-entrant, cross-platform, standard error codes, clear memory allocation rules, etc.)

**Comment by jminor** [comment]
Based on feedback from some vendors, we might want C++ instead of C. Let us know if you have opinions about this.

**Comment by quelsolaar** [comment]
My personal opinion, is that C is the right language to implement the core since it is fast and can be called by almost all languages, however i think the interface on top should be in whatever languages there users feel most comfortable with. If the feedback is that a C++ interface is useful then we should get on that. I have a few things I want to clean up in the core, but i can take a stab at a C++ interface right after.

**Comment by ssteinbach** [comment]
For wrapping the C/C++ API, some notes on various options:
https://github.com/PixarAnimationStudios/OpenTimelineIO/wiki/Wrapping-OTIO-C-C---In-Python

**Comment by quelsolaar** [comment]
If there is a C++ wrapper around the C implementation, and you want to wrap it in to a higher level language (and possibly use a tool to do so) you can obviously choose to wrap either the C implementation or the C++ wraper. I don't even think its a terrible idea to have multiple people write wrappers for different and even the same language and then see what turns out to be popular.

**Comment by ssteinbach** [comment]
Yeah, thats a great suggestion.  Another suggestion was to provide both Boost::Python and PyBind11 bindings since they're fairly similar - that way applications that have `boost` bindings can use those and those that don't can go with `pybind11`.  We're still mulling it over, so its great to get more feedback on this!

**Comment by MartinDelille** [comment]
@ssteinbach Ok I found your work here: #319

**Comment by ssteinbach** [comment]
For more information on this, see @davidbaraff's work in #391.

**Comment by ssteinbach** [comment]
See #540

**Comment by ssteinbach** [comment]
Landed!
