### ISSUE TITLE
`effect_name` vs schema name

### ISSUE THREAD

**Issue by palemieux** [PixarAnimationStudios/OpenTimelineIO#727]
The serialization of `LinearTimeWarp` includes both `"effect_name": "LinearTimeWarp"` and `"OTIO_SCHEMA": "LinearTimeWarp.1"`.

Couple of questions:

- What is the difference in semantics between `effect_name` and the value of `OTIO_SCHEMA` for the `Effect` class and its sublcasses?
- Is it an error for `"effect_name"` to not be equal to `"LinearTimeWarp"` when `"OTIO_SCHEMA" : "LinearTimeWarp.1"`

**Comment by reinecke** [comment]
In general, the schema tends to dictate the otio semantics of the behavior, but the `effect_name` might actually contain the name of the effect in the originating DCC. Given that many effects (time effects included) aren't throughly modeled in OTIO, it can be handy to use a near analog in OTIO while it may not be exactly the same effect.

The main use of this is to informally add support for effects that may not be fully modeled in OTIO.

For instance, a complex time remap from a DCC might be represented as a `LinearTimeWarp` in OTIO and have detailed retiming information placed in the format-specific namespace in the metadata dictionary for that effect instance. OTIO and other format adapters can treat that effect with the `LinearTimeWarp` schema semantics, but if the original adapter is invoked it could still detect the original effect type and translate it back accurately. Similarly, scripts written by consumers of the OTIO representation might be able to reach in and gather useful information even if the effect's behavior is represented by OTIO in a "Lossy" way.

In general, we envision that this sort of convention is used as a way for the community to iterate pragmatically, then after some consensus is reached we can formally adopt a new first-class schema to represent the use case.

**Comment by palemieux** [comment]
> In general, we envision that this sort of convention is used as a way for the community to iterate pragmatically,
> then after some consensus is reached we can formally adopt a new first-class schema to represent the use case.

Understood. In the case of `LinearTimeWarp.1` it is therefore an error for `effect_name` to contain anything but `"LinearTimeWarp"`, right?

**Comment by reinecke** [comment]
It can contain something other than `LinerTimeWarp`. You could be representing some other kind of time effect as a `LinearTimeWarp.1`. Using a value other than `LinearTimeWarp` for the `effect_name` is the way you convey to consumers that a `LinearTimeWarp.1` is being used to approximate a different effect that isn't modeled by OpenTimelineIO. Generally you would use a value for `effect_name` that has some meaning in the originating format.

**Comment by palemieux** [comment]
@reinecke Thanks!

**Comment by reinecke** [comment]
Closing issue, feel free to reopen if other questions come up.

**Comment by jminor** [comment]
One other clarification that might be good to record here: OTIO has very few Effect classes because this part of the schema has not been fleshed out much yet, but we don't intend to make different schema for every effect type in the future, since there are so many. The subclass TimeEffect is meant to cover any and all timing effects, of which only subclasses LinearTimeWarp and FreezeFrame are currently available.

Since there are many named, or unnamed, timing effects in various NLEs, we intend to implement just a few, including a catch-all (as yet unnamed) subclass which simply stores a mapping of output to input frames. Any crazy timing effect that jumps all over the place could be stored for interchange in OTIO as a time-mapping in this catch-all timing effect.

The separate effect_name field makes more sense in that context. For example, a "Speed Boost" effect in Avid Media Composer is non-linear, and so would not be a LinearTimeWarp. Instead it would be represented as the frame-mapping schema, but would retain "Speed Boost" in the effect_name. This allows generic handling of the time effect via the OTIO schema class, or more Avid-specific handling if the name "Speed Boost" is meaningful in a specific workflow or adapter.

The same is meant to apply for other non-timing effects. We can have OTIO's schema model a limited number of classes, without having to implement every effect in the universe. For timing effects, we have to use subclasses only where the _behavior_ of the effect matters to OTIO for timing calculations. For effects where OTIO just passes along the parameters to someone else without differing behavior, then OTIO doesn't need to have schema subclasses for those things.
