### ISSUE TITLE
FCP XML outputs not recognised by Resolve 17

### ISSUE THREAD

**Issue by donquibeats** [PixarAnimationStudios/OpenTimelineIO#839]
## Feature Request & Description

When creating an FCP XML file by calling `otio.adapters.write_to_file()`, the default output does _not_ include a format structure (within `<project><children><media>`).

Because this `<format>` is absent, DaVinci Resolve won't load the XML file as a valid timeline. No errors are thrown, but no timeline appears in Resolve.

Transplanting a format tag from a different XML file into the XML generated by OTIO results in a file that Resolve will read, so it seems that the <format> tag is the missing piece.

Could `write_to_file()` be expanded, or its default behaviour changed, so that the resultant XML contains a <format> tag?

## Context

The current XML output will import successfully into Adobe Premiere, and if Premiere is used to export another XML file, a larger file is created. This second file successfully imports into Resolve.

Tested in DaVinci Resolve 17 beta.

**Comment by donquibeats** [comment]
[FCPXML_formatTagExample_9Dec20.txt](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/5665459/FCPXML_formatTagExample_9Dec20.txt)

This attachment is an example of the <format> section of the XML file, that I had to copy into the OTIO-generated XML file in order to make Resolve recognise it.

**Comment by reinecke** [comment]
This sounds a lot like #499 has been long standing but I think it's slightly different. Would you be able to provide a sample OTIO that exports broken, but works with the added `format` XML?

**Comment by donquibeats** [comment]
[Tests-2020-12-16 for Resolve FCP XML issue.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/5701861/Tests-2020-12-16.for.Resolve.FCP.XML.issue.zip)

Sure. Attached is a zip file containing 2 XML's and the equivalent OTIO.

The XML marked 'original' is what comes straight out of OTIO's adapters.write_to_file(). Resolve, instead of reading it correctly, treats the entire timeline as one valid clip.

For the XML marked 'patched', I manually pasted the <format> tag data (lines 15-48) from a Premiere-generated FCP XML file. The patched file opens correctly in Resolve (17.0 beta) and shows the full timeline.

Hopefully that helps?

**Comment by pedrolabonia** [comment]
> going forward, I wonder if using a python api in resolve might be able to directly read OTIO files without having to go through this format

Hey @ssteinbach, I'm pretty familiar with Resolve's API. You _could_ do that. There are some limitations on the editing part of Resolve's API, but you would need to find the media in the `MediaPool` object, set in/out and append in order each one on the timeline. You could even try to map repositions/effects, but as far as I know OTIO haven't tried to standardize that yet.

I'm pretty familiar with Resolve's API, having written a wrapper library around it, and I could give that a shot. How would we go about that, since it needs to be executed from inside Resolve in the console or outside for Studio users only.

**Comment by jminor** [comment]
@pedrolabonia if you want to go that route, I suggest extending this Resolve plugin: https://github.com/eric-with-a-c/resolve-otio 

However, the XML tag fix outlined above is probably a quick fix for someone wanting to contribute to OTIO & able to test in Resolve.

Since Resolve supports so many import/export formats already, picking the best one isn't obvious. This is a great problem to have :) Also, it is fine to have both an adapter-based workflow and a plugin-based workflow for working with OTIO and Resolve.
