### ISSUE TITLE
Add C++ conveniences

### ISSUE THREAD

**Issue by darbyjohnston** [PixarAnimationStudios/OpenTimelineIO#922]
It would be nice to add a couple of convenience functions to streamline the C++ code that works with the SerializableObject::Retainer type, specifically functions for casting and operator overloads that makes the type feel more like a regular pointer.

Old:
```
if (auto freezeFrame = dynamic_cast<otio::FreezeFrame*>(effect.value)) {
```

New:
```
if (auto freezeFrame = otio::dynamic_retainer_cast<otio::FreezeFrame>(effect)) {
```

Old:
```
if (!_media_reference.value->available_range()) {
```

New:
```
if (!_media_reference->available_range()) {
```

**Comment by meshula** [comment]
Just a thought, once you've added -> overloads to the retainer, the primary reason for fetching the pointer out of the retainer is less compelling. 

I was thinking that dynamic_retainer_cast might more usefully be implemented in the same pattern as we can see in https://en.cppreference.com/w/cpp/memory/shared_ptr/pointer_cast where the smart pointer casts are used to up/down/reinterpret cast between smart pointers (td::static_pointer_cast, std::dynamic_pointer_cast, std::const_pointer_cast, std::reinterpret_pointer_cast). The equivalent, s/pointer/retainer/, might be the way to go, as that would allow dynamic up and  down casting within the OTIO hierarchy and stay within the retainer counting regime rather than decanting the value into the realm of naked pointers. It would also provide a familiar affordance to C++ programmers.

**Comment by darbyjohnston** [comment]
Merged with:
https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/923
